# Generated by Django 2.0.2 on 2018-05-29 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20180529_1711'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='timestemp',
            new_name='uploadtime',
        ),
    ]
