# Generated by Django 2.0.2 on 2018-05-29 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20180529_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='uploadtime',
        ),
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
